### ISSUE TITLE
matlab2tikz, more ideas

### ISSUE THREAD

**Issue by nschloe** [egeerardyn/awesome-LaTeX#34]
Hi Egon!

Going through this list, I was missing matlab2tikz/matplotlib2tikz. Why not include those? More ideas: https://github.com/nschloe/betterbib, https://github.com/nschloe/blacktex.

**Comment by egeerardyn** [comment]
Hi Nico 😄 that has been a while. I hope you are doing well.

Indeed, I should include those. Unfortunately, I haven't put much time into this list since I have moved from academia to industry (which is nice to do, except for migrating from LaTeX to MS Office 😢 ).

When I find some time, I'll try to include them (and otherwise, feel free to make a PR)

**Comment by nschloe** [comment]
> to MS Office

Oh noes!

I'll fix a PR.
